on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  issue_comment:

jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write
      contents: write
      checks: write

    steps:
      - name: PR Agent
        uses: the-pr-agent/pr-agent@main
        env:
          OPENAI__KEY: ${{ secrets.OPENAI_KEY }}
          OPENAI__API_BASE: https://litellm.lrate.top/v1
        
          config.model: "gpt-oss-120b"
          config.fallback_models: '["gpt-oss-120b"]'
        
          # 关键配置
          config.custom_model_max_tokens: "131072"
        
          # GPT-OSS 属于推理模型，建议开启
          config.custom_reasoning_model: "true"
